[versions]
gdx = "1.11.0"
nexus-publish = "1.3.0"
imgui="1.86.10"
spotless = "6.10.0"
[libraries]
gdx-core = { module = "com.badlogicgames.gdx:gdx", version.ref = "gdx" }
gdx-backend-lwjgl3 = { module = "com.badlogicgames.gdx:gdx-backend-lwjgl3", version.ref = "gdx" }
imgui-binding = { module = "io.github.spair:imgui-java-binding", version.ref = "imgui"}
imgui-lwgjl3 = { module = "io.github.spair:imgui-java-lwjgl3", version.ref = "imgui"}
imgui-natives-linux = { module = "io.github.spair:imgui-java-natives-linux", version.ref = "imgui"}
imgui-natives-macos = { module = "io.github.spair:imgui-java-natives-macos", version.ref = "imgui"}
imgui-natives-windows = { module = "io.github.spair:imgui-java-natives-windows", version.ref = "imgui"}
[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish"}
